frontend/src/metabase/containers/about/components/AboutService.jsx

Show data API docs on the official website.

docs: add data API

---

frontend/src/metabase/routes.jsx
frontend/src/metabase/visualizations/components/ScalarValue.jsx
frontend/src/metabase/visualizations/visualizations/Scalar.jsx

Disabled auto compact large number when using number visualization.

fix: scalar value display compact error

---

frontend/src/metabase/containers/home/components/HomeFooter.jsx

Mailto should created by external link.

fix: mailto should created by external link

---

frontend/src/metabase/css/core/overflow.css
frontend/src/metabase/visualizations/components/ScalarValue.jsx

fix: hide overflow x scrollbar

---

webpack.config.js

Fix ESLint unable to resolve path to module.

build: fix unable to resolve path to module

---

frontend/src/metabase/containers/about/components/AboutService.jsx

fix: API docs link

---

frontend/src/metabase/lib/formatting.js

Field display precision changed from 2 to 4

fix: field precision not enough

---

frontend/src/metabase/lib/formatting.js
frontend/src/metabase/query_builder/components/TableDictionary.jsx
frontend/src/metabase/query_builder/components/ToggleCreateType.jsx
frontend/src/metabase/query_builder/components/view/ViewHeader.jsx

feat: swap chart mode to SQL mode

---

frontend/src/metabase/query_builder/components/NativeQueryEditor.css
frontend/src/metabase/query_builder/components/view/DarkModeButton.jsx
frontend/src/metabase/redux/control.js

Better color matching for sql editor, protect your eyes

feat: better color matching for sql editor

---

frontend/src/metabase/containers/about/components/AboutService.jsx
frontend/src/metabase/nav/containers/Navbar.jsx
frontend/src/metabase/pricing/index.jsx

Pricing page add contact entrance. Rename data upload name in home. And update api link in about page.

feat: add pricing contact and replace api url

---

frontend/src/metabase/containers/news/components/ActionButtons.jsx
frontend/src/metabase/containers/news/detail.jsx
frontend/src/metabase/containers/news/publish.jsx
frontend/src/metabase/lib/urls.js

Change article url to short id for better seo

feat: short id article for seo

---

frontend/src/metabase/redux/user.js

feat: bind user info to ARMS

---

frontend/src/metabase/lib/formatting.js
frontend/src/metabase/query_builder/components/TableChartInfo.jsx
frontend/src/metabase/query_builder/components/TableUpgrade.jsx

Invalid group specifier name in Safari.

fix: invalid group specifier name in Safari

---

frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
frontend/src/metabase/visualizations/lib/apply_tooltips.js
frontend/src/metabase/visualizations/lib/settings/series.js

Improved hover performance of chart tooltips.

perf: improved hover performance of chart tooltips

---

frontend/src/metabase/containers/customUpload/components/Result/index.jsx

Rename "Personal Upload" to "My Dataset".

feat: rename personal upload

---

frontend/src/metabase/containers/about/components/AboutHeader.jsx
frontend/src/metabase/dashboard/containers/ArchiveDashboardModal.jsx
frontend/src/metabase/entities/dashboards.js
frontend/src/metabase/entities/questions.js
frontend/src/metabase/query_builder/containers/ArchiveQuestionModal.jsx

Redirect after archive dashboard.

fix: redirect after archive dashboard

---

frontend/src/metabase/components/Popover.jsx

fix: popover position overflow

---

Dockerfile
src/metabase/query_processor/middleware/cache.clj

The user sees the cache forever and then updates the cache asynchronously. Improve user experience and solve the slow loading problem.

feat: async update chart cache 

---

frontend/src/metabase/components/PreviewDashboardCard.jsx
frontend/src/metabase/containers/dashboards/components/Dashboards/getListColums.jsx
frontend/src/metabase/query_builder/components/TableChartInfo.css
frontend/src/metabase/query_builder/components/TableChartInfo.jsx

feat: show deprecated table tip

---

frontend/src/metabase/containers/dashboards/components/Dashboards/List.jsx
frontend/src/metabase/containers/dashboards/components/Dashboards/getListQueryParams.js
frontend/src/metabase/containers/search/components/Tabs/index.jsx

The creator page's own dashboards and charts can be sorted by created_at. Find what you want faster

feat: creator sort created_at

---

frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.css
frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.jsx

Allow closing tool popover when creating a dashboard.

feat: allow closing tool popover

---

frontend/src/metabase/components/DownloadButton.jsx
frontend/src/metabase/dashboard/components/DashCard.css
frontend/src/metabase/dashboard/components/DashCard.jsx
frontend/src/metabase/new-service.js
frontend/src/metabase/query_builder/components/QueryDownloadWidget.jsx
frontend/src/metabase/query_builder/components/TableChartInfo.jsx
frontend/src/metabase/query_builder/components/view/ViewFooter.jsx

- Allow download unsave chart data.
- Allow download chart data in dashboard.

feat: allow download unsave chart data

---

frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
frontend/src/metabase/growth/components/GaLayout.jsx
frontend/src/metabase/growth/components/GaSidebar.tsx
frontend/src/metabase/growth/components/Logo.jsx
frontend/src/metabase/growth/components/StateProvider.jsx
frontend/src/metabase/growth/components/User.jsx
frontend/src/metabase/growth/components/config_panel/ConfigConnectors.jsx
frontend/src/metabase/growth/components/config_panel/ConfigFinish.jsx
frontend/src/metabase/growth/components/config_panel/ConfigMapping.jsx
frontend/src/metabase/growth/components/config_panel/ConfigProject.jsx
frontend/src/metabase/growth/containers/About.jsx
frontend/src/metabase/growth/containers/CreateProject.jsx
frontend/src/metabase/growth/containers/Home.jsx
frontend/src/metabase/growth/css/index.css
frontend/src/metabase/growth/css/layout.css
frontend/src/metabase/growth/css/utils.css
frontend/src/metabase/growth/utils/dashboard.jsx
frontend/src/metabase/public/components/EmbedFrame.jsx
frontend/src/metabase/public/containers/PublicDashboard.jsx
frontend/src/metabase/routes.jsx
frontend/src/metabase/routesLazyLoad.js

Feat growth analytics v0.1

---

frontend/src/metabase/growth/components/CreateProjectModal.jsx
frontend/src/metabase/growth/components/GaProjectSearch.jsx
frontend/src/metabase/growth/containers/Campaigns.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/utils/utils.tsx
frontend/src/metabase/nav/containers/FgaNavbar/FgaNavbar.jsx

Feat growth analytics v2

---

frontend/src/metabase/auth/components/LoginModalInner.jsx
frontend/src/metabase/auth/components/SignInPanel.jsx
frontend/src/metabase/growth/components/CreateProjectModal.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/nav/containers/FgaNavbar/FgaNavbar.jsx
frontend/src/metabase/new-service.js

commit approve

---

frontend/src/metabase/growth/containers/Project.jsx

commit add cohort_list

---

frontend/src/metabase/growth/components/GaSidebar.tsx
frontend/src/metabase/growth/components/LoadingDashboard.jsx
frontend/src/metabase/growth/containers/CustomAnalysis.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/css/utils.css
frontend/src/metabase/growth/utils/data.jsx
frontend/src/metabase/growth/utils/utils.tsx
frontend/src/metabase/public/containers/PublicDashboard.jsx

Feat update menu

---

frontend/src/metabase/growth/containers/MyAnalysis.jsx

Reverts footprintanalytics/footprint-web#773

Revert "Feat update menu"

---

frontend/src/metabase/growth/components/GaSidebar.tsx
frontend/src/metabase/growth/components/LoadingDashboard.jsx
frontend/src/metabase/growth/containers/CustomAnalysis.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/css/utils.css
frontend/src/metabase/growth/utils/data.jsx
frontend/src/metabase/growth/utils/utils.tsx
frontend/src/metabase/public/containers/PublicDashboard.jsx

Reverts footprintanalytics/footprint-web#783

Revert "Revert "Feat update menu""

---

frontend/src/metabase/growth/components/GaSidebar.tsx
frontend/src/metabase/growth/components/LoadingDashboard.jsx
frontend/src/metabase/growth/containers/CustomAnalysis.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/css/utils.css
frontend/src/metabase/growth/utils/data.jsx
frontend/src/metabase/growth/utils/utils.tsx
frontend/src/metabase/public/containers/PublicDashboard.jsx

Reverts footprintanalytics/footprint-web#784

Revert "Revert "Revert "Feat update menu"""

---

frontend/src/metabase/growth/components/Community/StatisticIndex.jsx
frontend/src/metabase/growth/containers/CohortList.jsx
frontend/src/metabase/growth/containers/Community.jsx
frontend/src/metabase/growth/containers/PotentialUsers/index.jsx
frontend/src/metabase/growth/containers/price/index.jsx
frontend/src/metabase/nav/containers/FgaNavbar/FgaNavbar.jsx
frontend/src/metabase/new-service.js

Feat member info

---

frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/utils/data.jsx

add tokennomics and mask

---

frontend/src/metabase/growth/components/Community/StatisticIndex.jsx
frontend/src/metabase/growth/components/DashboardMask.jsx
frontend/src/metabase/growth/containers/ChannelList.jsx
frontend/src/metabase/growth/containers/ConnectorList.jsx
frontend/src/metabase/growth/containers/Project.jsx

group by integrations

---

frontend/src/metabase/growth/containers/CampaignListNew.jsx
frontend/src/metabase/growth/utils/data.jsx

Feat add ca

---

frontend/src/metabase/growth/components/Modal/UploadMappingModal.jsx
frontend/src/metabase/growth/containers/MyAnalysis.jsx
frontend/src/metabase/growth/containers/SocialConnectList.jsx
frontend/src/metabase/growth/utils/data.jsx
frontend/src/metabase/lib/oss.js
frontend/src/metabase/new-service.js
package.json
yarn.lock

Feat upload mapping

---

frontend/src/metabase/public/containers/PublicDashboard.jsx

able to change param in dashboard

---

frontend/src/metabase/growth/components/Community/WalletList.jsx
frontend/src/metabase/growth/components/ProjectInfo.jsx
frontend/src/metabase/growth/components/buttons/UploadWallets.jsx
frontend/src/metabase/growth/containers/Airdrop.jsx
frontend/src/metabase/growth/containers/CohortList.jsx
frontend/src/metabase/growth/containers/Community.jsx
frontend/src/metabase/growth/containers/PotentialUsers/CreateFliterCohort.jsx
frontend/src/metabase/growth/containers/PotentialUsers/ItemFilter.jsx
frontend/src/metabase/growth/containers/PotentialUsers/index.css
frontend/src/metabase/growth/containers/PotentialUsers/index.jsx
frontend/src/metabase/growth/containers/Project.jsx
frontend/src/metabase/growth/containers/price/index.jsx
frontend/src/metabase/growth/utils/data.jsx
frontend/src/metabase/growth/utils/utils.tsx

1.  move tokenomic into free
2. change style of 'add filter' button
3. release all action button
4. adjust the limit of upload wallets

adjust project

---

frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.css
frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.styled.jsx
frontend/src/metabase/containers/dataApi/price/index.css
frontend/src/metabase/containers/dataApi/price/index.jsx
frontend/src/metabase/growth/containers/price/index.css
frontend/src/metabase/pricing_v3/index.jsx

feat: update API pricing

---

frontend/src/metabase/containers/research/components/ChartArea.jsx
frontend/src/metabase/containers/research/components/DashboardArea.jsx
frontend/src/metabase/public/containers/PublicDashboard.jsx
frontend/src/metabase/public/containers/PublicQuestion.jsx

Reverts footprintanalytics/footprint-web#1141

Revert "feat: research api tip chart"

---

frontend/src/metabase/visualizations/components/Visualization.jsx

调整growthly not data chart 提示

---

frontend/src/metabase/visualizations/components/Visualization.jsx

调整no data 文案
